# Generated by Django 4.2.8 on 2023-12-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institute_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_duration', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Indl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Number', models.CharField(max_length=200)),
                ('Rank', models.CharField(choices=[('General', 'General'), ('Lt General', 'Lt General'), ('Maj General', 'Maj General'), ('Brig General', 'Brig General'), ('Colonel', 'Colonel'), ('Lt Colonel', 'Lt Colonel'), ('Major', 'Major'), ('Captain', 'Captain'), ('Lt', 'Lt'), ('2 Lt', '2 Lt'), ('MWO', 'MWO'), ('SWO', 'SWO'), ('WO', 'WO'), ('Sgt', 'Sgt'), ('Cpl', 'Cpl'), ('L Cpl', 'L Cpl'), ('Snk', 'Snk'), ('Civ', 'Civ')], max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Svcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Air Force', 'Air Force'), ('Jt Trg', 'Jt Trg')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('svcs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.svcs')),
            ],
        ),
        migrations.CreateModel(
            name='GovtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('svcs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.svcs')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('svcs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.svcs')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(to='myapp.indl'),
        ),
    ]
