# Generated by Django 4.2.8 on 2023-12-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='svcs',
            name='name',
            field=models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Air Force', 'Air Force'), ('Jt Trg', 'Jt Trg'), ('AFD', 'AFD')], max_length=20),
        ),
    ]
