# Generated by Django 4.2.8 on 2023-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sections_alter_svcs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='image',
            field=models.ImageField(default=2, upload_to='section_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
