# Generated by Django 4.2.8 on 2023-12-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sections_image_alter_sections_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='template_name',
            field=models.CharField(default='armydashboard.html', max_length=200),
        ),
    ]
