# Generated by Django 4.2.8 on 2023-12-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sections_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='template_name',
            field=models.CharField(default='armydashboard', max_length=200),
        ),
    ]
